name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Change dir
      run: |
        cd csharp
        cd gradebook_v3
        cd src
        cd GradeBook
    - name: Print dir elements
      run: |
        ls
    - name: Restore dependencies
      working-directory: csharp/gradebook_v3/src/GradeBook/
      run: dotnet restore
    - name: Build
      working-directory: csharp/gradebook_v3/src/GradeBook/
      run: dotnet build --no-restore
    - name: Test
      working-directory: csharp/gradebook_v3/src/GradeBook/
      run: dotnet test --no-build --verbosity normal
    - name: Run
      working-directory: csharp/gradebook_v3/src/GradeBook/
      run: dotnet run Abhijeet
